import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./component/navbar";
import Footer from "./component/footer";
const inter = Inter({ subsets: ["latin"] });
import {Providers} from "./providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body  className={inter.className} >
      <Providers>

        <Navbar/>
        {children}
        <Footer/>
        </Providers>

        </body> 
    </html>
  );
}
