"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./component/navbar";
import Footer from "./component/footer";
const inter = Inter({ subsets: ["latin"] });
import { Providers } from "./providers";
import { useEffect, useState } from "react";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({ children }) {
  const [navlinks , setNavLinks] = useState([
    { name: 'Home', link: '#home' ,isActive : true },
    { name: 'Projects', link: '#projects' ,isActive : false },
    { name: 'Services', link: '#services' ,isActive : false },
    { name: 'Testimonials', link: '#testimonials' ,isActive : false },
  ])
  const [selectedSection, setSelectedSection] = useState(null);
  const [id , setId] = useState(null)
 
  useEffect(() => {
    const handleScroll = () => {
      const scrollPosition = window.scrollY;
      const sections = document.querySelectorAll("section[id]");
      // console.log({sections}, "section");
      sections.forEach((section) => {
        const sectionTop = section.offsetTop;
        const sectionHeight = section.clientHeight;
        if (
          scrollPosition >= sectionTop &&
          scrollPosition < sectionTop + sectionHeight
        ) {
          setSelectedSection(section.id);
        }
      });
    };

    window.addEventListener("scroll", handleScroll);

    // Clean up event listener
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);
  return (
    // <html lang="en" suppressHydrationWarning={true}>
    <html lang="en" >
      <body className={inter.className} >
        <Providers>
        <Navbar navlinks={navlinks} selectedSection={selectedSection} setNavLinks={setNavLinks} />
      
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
